FROM node:16-alpine
RUN apt-get update && apt-get install -y nginx
RUN mkdir /code
WORKDIR /code
ADD ./package.json .
ADD ./package-lock.json .
RUN npm install
ENV NODE_ENV production
RUN npm run build
