version: '2'

services:
#  postgres:
#    extends:
#      file: ../docker-common.yml
#      service: postgres

#  redis:
#    extends:
#      file: ../docker-common.yml
#      service: redis

  smart_backend:
    build:
      context: backend
      dockerfile: Dockerfile.prod
    image: geoffd/smart-backend-prod:${TAG:-latest}
    restart: always
    depends_on:
      - postgres
      - redis

  smart_frontend:
    extends:
      file: ../docker-common.yml
      service: smart_frontend
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    ports:
      - "${EXTERNAL_FRONTEND_PORT:-8080}:8080"
    command: nginx -c /code/nginx.conf -g "daemon off;"

volumes:
  smart_pgdata:
  smart_data:
