version: '2.1'

services:
  postgres:
    extends:
      file: ../docker-common.yml
      service: postgres

  redis:
    extends:
      file: ../docker-common.yml
      service: redis

  smart_backend:
    extends:
      file: ../docker-common.yml
      service: smart_backend
    build:
      context: ../../backend/
      dockerfile: docker/Dockerfile.prod
    image: rti/smart-backend-prod:R_0_0_1
    restart: always
    depends_on:
      - postgres
      - redis

  smart_frontend:
    extends:
      file: ../docker-common.yml
      service: smart_frontend
    build: ../../frontend/
    image: rti/smart-frontend-prod:R_0_0_1
    ports:
      - "${EXTERNAL_FRONTEND_PORT:-80}:80"
    command: node_modules/.bin/webpack --watch

  celery_worker:
    extends:
      file: ../docker-common.yml
      service: celery_worker
    build:
      context: ../../backend/
      dockerfile: docker/Dockerfile.prod
    image: rti/smart-backend-prod:R_0_0_1
    depends_on:
      - postgres
      - redis
      - smart_backend

volumes:
  smart_pgdata:
    external: true
    name: vol_smart_pgdata
  smart_data:
    external: true
    name: vol_smart_data
